/** Pool for Sentence Builder — 5 sentences per daily set across 90 rotation days. */
export const ALL_SENTENCE_BUILDER = [
  { prompt: "Make a sentence about daily routine.", words: ["every", "morning", "I", "drink", "coffee", "before", "work"], answer: "I drink coffee before work every morning" },
  { prompt: "Describe what someone is doing.", words: ["she", "is", "reading", "a", "book", "in", "the", "garden"], answer: "she is reading a book in the garden" },
  { prompt: "Talk about the past.", words: ["yesterday", "we", "went", "to", "the", "beach", "together"], answer: "yesterday we went to the beach together" },
  { prompt: "Make a question.", words: ["where", "did", "you", "buy", "that", "beautiful", "hat"], answer: "where did you buy that beautiful hat" },
  { prompt: "Describe the weather.", words: ["it", "was", "raining", "heavily", "all", "day", "long"], answer: "it was raining heavily all day long" },
  { prompt: "Express a preference.", words: ["I", "prefer", "tea", "to", "coffee", "in", "the", "winter"], answer: "I prefer tea to coffee in the winter" },
  { prompt: "Talk about a plan.", words: ["we", "are", "going", "to", "visit", "the", "museum", "tomorrow"], answer: "we are going to visit the museum tomorrow" },
  { prompt: "Describe a place.", words: ["the", "park", "near", "our", "house", "is", "very", "beautiful"], answer: "the park near our house is very beautiful" },
  { prompt: "Make a polite request.", words: ["could", "you", "please", "pass", "me", "the", "salt"], answer: "could you please pass me the salt" },
  { prompt: "Talk about an experience.", words: ["I", "have", "never", "eaten", "sushi", "before", "today"], answer: "I have never eaten sushi before today" },
  { prompt: "Describe a feeling.", words: ["she", "felt", "very", "nervous", "before", "her", "job", "interview"], answer: "she felt very nervous before her job interview" },
  { prompt: "Give advice.", words: ["you", "should", "drink", "more", "water", "every", "day"], answer: "you should drink more water every day" },
  { prompt: "Describe a habit.", words: ["he", "always", "reads", "the", "news", "after", "breakfast"], answer: "he always reads the news after breakfast" },
  { prompt: "Make a comparison.", words: ["this", "book", "is", "more", "interesting", "than", "that", "one"], answer: "this book is more interesting than that one" },
  { prompt: "Talk about the future.", words: ["I", "will", "call", "you", "as", "soon", "as", "I", "arrive"], answer: "I will call you as soon as I arrive" },
  { prompt: "Describe a problem.", words: ["the", "train", "was", "late", "so", "we", "missed", "the", "show"], answer: "the train was late so we missed the show" },
  { prompt: "Express surprise.", words: ["I", "cannot", "believe", "how", "fast", "the", "time", "has", "passed"], answer: "I cannot believe how fast the time has passed" },
  { prompt: "Describe an action in progress.", words: ["they", "are", "building", "a", "new", "school", "near", "the", "park"], answer: "they are building a new school near the park" },
  { prompt: "Talk about a rule.", words: ["you", "must", "not", "use", "your", "phone", "during", "class"], answer: "you must not use your phone during class" },
  { prompt: "Describe something you like.", words: ["I", "really", "enjoy", "walking", "by", "the", "river", "at", "sunset"], answer: "I really enjoy walking by the river at sunset" },
  { prompt: "Talk about homework.", words: ["I", "finished", "my", "homework", "before", "dinner", "tonight"], answer: "I finished my homework before dinner tonight" },
  { prompt: "Describe a pet.", words: ["the", "cat", "sleeps", "on", "the", "warm", "windowsill", "every", "afternoon"], answer: "the cat sleeps on the warm windowsill every afternoon" },
  { prompt: "Make a sentence about travel.", words: ["we", "took", "a", "train", "to", "the", "capital", "last", "weekend"], answer: "we took a train to the capital last weekend" },
  { prompt: "Talk about music.", words: ["she", "plays", "the", "piano", "better", "than", "anyone", "I", "know"], answer: "she plays the piano better than anyone I know" },
  { prompt: "Describe breakfast.", words: ["he", "usually", "eats", "toast", "with", "jam", "and", "orange", "juice"], answer: "he usually eats toast with jam and orange juice" },
  { prompt: "Talk about friendship.", words: ["my", "best", "friend", "has", "lived", "next", "door", "for", "years"], answer: "my best friend has lived next door for years" },
  { prompt: "Describe a sport.", words: ["they", "practice", "football", "every", "Tuesday", "after", "school"], answer: "they practice football every Tuesday after school" },
  { prompt: "Talk about shopping.", words: ["I", "bought", "fresh", "vegetables", "at", "the", "market", "this", "morning"], answer: "I bought fresh vegetables at the market this morning" },
  { prompt: "Describe the evening.", words: ["the", "sun", "set", "behind", "the", "hills", "in", "golden", "light"], answer: "the sun set behind the hills in golden light" },
  { prompt: "Talk about learning English.", words: ["we", "learn", "new", "vocabulary", "in", "every", "single", "lesson"], answer: "we learn new vocabulary in every single lesson" },
  { prompt: "Describe a busy day.", words: ["I", "had", "meetings", "from", "nine", "until", "five", "today"], answer: "I had meetings from nine until five today" },
  { prompt: "Talk about a film.", words: ["the", "movie", "was", "longer", "than", "we", "had", "expected"], answer: "the movie was longer than we had expected" },
  { prompt: "Describe helping someone.", words: ["she", "helped", "her", "neighbor", "carry", "the", "heavy", "boxes"], answer: "she helped her neighbor carry the heavy boxes" },
  { prompt: "Talk about a holiday.", words: ["we", "always", "decorate", "the", "house", "before", "winter", "holidays"], answer: "we always decorate the house before winter holidays" },
  { prompt: "Describe a mistake.", words: ["I", "accidentally", "sent", "the", "email", "to", "the", "wrong", "person"], answer: "I accidentally sent the email to the wrong person" },
  { prompt: "Talk about health.", words: ["drinking", "water", "helps", "you", "stay", "focused", "at", "work"], answer: "drinking water helps you stay focused at work" },
  { prompt: "Describe a city.", words: ["the", "streets", "were", "crowded", "with", "tourists", "that", "summer"], answer: "the streets were crowded with tourists that summer" },
  { prompt: "Talk about a gift.", words: ["he", "gave", "his", "sister", "a", "book", "for", "her", "birthday"], answer: "he gave his sister a book for her birthday" },
  { prompt: "Describe being tired.", words: ["I", "was", "so", "tired", "that", "I", "fell", "asleep", "immediately"], answer: "I was so tired that I fell asleep immediately" },
  { prompt: "Talk about cooking.", words: ["we", "followed", "the", "recipe", "carefully", "and", "the", "cake", "rose", "perfectly"], answer: "we followed the recipe carefully and the cake rose perfectly" },
  { prompt: "Describe a phone call.", words: ["she", "called", "to", "say", "she", "would", "be", "ten", "minutes", "late"], answer: "she called to say she would be ten minutes late" },
  { prompt: "Talk about nature.", words: ["birds", "sang", "in", "the", "trees", "as", "we", "walked", "through", "the", "forest"], answer: "birds sang in the trees as we walked through the forest" },
  { prompt: "Describe a classroom.", words: ["the", "students", "raised", "their", "hands", "to", "answer", "the", "question"], answer: "the students raised their hands to answer the question" },
  { prompt: "Talk about time.", words: ["there", "is", "never", "enough", "time", "to", "finish", "everything"], answer: "there is never enough time to finish everything" },
  { prompt: "Describe rain.", words: ["we", "waited", "under", "the", "bridge", "until", "the", "storm", "passed"], answer: "we waited under the bridge until the storm passed" },
  { prompt: "Talk about a library.", words: ["you", "must", "speak", "quietly", "when", "you", "are", "inside", "the", "library"], answer: "you must speak quietly when you are inside the library" },
  { prompt: "Describe excitement.", words: ["the", "children", "were", "excited", "to", "see", "the", "parade"], answer: "the children were excited to see the parade" },
  { prompt: "Talk about email.", words: ["I", "received", "an", "important", "message", "from", "my", "teacher", "yesterday"], answer: "I received an important message from my teacher yesterday" },
  { prompt: "Describe a photograph.", words: ["the", "old", "photo", "reminded", "us", "of", "our", "summer", "holiday"], answer: "the old photo reminded us of our summer holiday" },
  { prompt: "Talk about a concert.", words: ["the", "band", "played", "their", "most", "famous", "song", "last"], answer: "the band played their most famous song last" },
  { prompt: "Describe fear.", words: ["he", "was", "afraid", "of", "speaking", "in", "front", "of", "strangers"], answer: "he was afraid of speaking in front of strangers" },
  { prompt: "Talk about a bicycle.", words: ["she", "rides", "her", "bicycle", "to", "work", "when", "the", "weather", "is", "nice"], answer: "she rides her bicycle to work when the weather is nice" },
  { prompt: "Describe a storm.", words: ["lightning", "lit", "up", "the", "sky", "over", "the", "ocean"], answer: "lightning lit up the sky over the ocean" },
  { prompt: "Talk about a doctor.", words: ["the", "doctor", "said", "I", "should", "rest", "for", "two", "days"], answer: "the doctor said I should rest for two days" },
  { prompt: "Describe a letter.", words: ["I", "wrote", "a", "thank-you", "note", "after", "the", "interview"], answer: "I wrote a thank-you note after the interview" },
  { prompt: "Talk about a restaurant.", words: ["the", "waiter", "brought", "our", "drinks", "before", "we", "ordered", "food"], answer: "the waiter brought our drinks before we ordered food" },
  { prompt: "Describe winter.", words: ["snow", "covered", "the", "roofs", "and", "the", "quiet", "streets"], answer: "snow covered the roofs and the quiet streets" },
  { prompt: "Talk about a dream.", words: ["I", "dreamed", "that", "I", "could", "fly", "above", "the", "mountains"], answer: "I dreamed that I could fly above the mountains" },
  { prompt: "Describe a bridge.", words: ["the", "old", "stone", "bridge", "crosses", "the", "slow", "river"], answer: "the old stone bridge crosses the slow river" },
  { prompt: "Talk about a festival.", words: ["thousands", "of", "people", "gathered", "in", "the", "town", "square"], answer: "thousands of people gathered in the town square" },
  { prompt: "Describe patience.", words: ["we", "waited", "patiently", "in", "line", "for", "over", "an", "hour"], answer: "we waited patiently in line for over an hour" },
  { prompt: "Talk about a camera.", words: ["he", "borrowed", "a", "camera", "to", "take", "photos", "at", "the", "wedding"], answer: "he borrowed a camera to take photos at the wedding" },
  { prompt: "Describe a mountain.", words: ["the", "path", "wound", "up", "the", "steep", "rocky", "slope"], answer: "the path wound up the steep rocky slope" },
  { prompt: "Talk about a neighbor.", words: ["our", "neighbor", "brought", "us", "soup", "when", "we", "were", "ill"], answer: "our neighbor brought us soup when we were ill" },
  { prompt: "Describe a clock.", words: ["the", "clock", "struck", "midnight", "as", "the", "year", "began"], answer: "the clock struck midnight as the year began" },
  { prompt: "Talk about a map.", words: ["we", "used", "a", "map", "to", "find", "the", "hidden", "trail"], answer: "we used a map to find the hidden trail" },
  { prompt: "Describe kindness.", words: ["a", "stranger", "helped", "me", "find", "my", "lost", "wallet"], answer: "a stranger helped me find my lost wallet" },
  { prompt: "Talk about a journal.", words: ["she", "writes", "in", "her", "journal", "every", "night", "before", "bed"], answer: "she writes in her journal every night before bed" },
  { prompt: "Describe a beach.", words: ["waves", "crashed", "against", "the", "rocks", "below", "the", "cliff"], answer: "waves crashed against the rocks below the cliff" },
  { prompt: "Talk about a key.", words: ["I", "forgot", "my", "keys", "and", "had", "to", "call", "a", "locksmith"], answer: "I forgot my keys and had to call a locksmith" },
  { prompt: "Describe a garden.", words: ["bees", "buzzed", "among", "the", "lavender", "and", "wild", "roses"], answer: "bees buzzed among the lavender and wild roses" },
  { prompt: "Talk about a speech.", words: ["the", "mayor", "gave", "a", "short", "speech", "at", "the", "opening"], answer: "the mayor gave a short speech at the opening" },
  { prompt: "Describe a sweater.", words: ["I", "knitted", "a", "warm", "sweater", "for", "my", "little", "cousin"], answer: "I knitted a warm sweater for my little cousin" },
  { prompt: "Talk about a bus.", words: ["the", "bus", "was", "so", "crowded", "that", "we", "had", "to", "stand"], answer: "the bus was so crowded that we had to stand" },
  { prompt: "Describe a star.", words: ["we", "lay", "on", "the", "grass", "and", "counted", "shooting", "stars"], answer: "we lay on the grass and counted shooting stars" },
  { prompt: "Talk about a password.", words: ["you", "should", "choose", "a", "strong", "password", "for", "your", "accounts"], answer: "you should choose a strong password for your accounts" },
  { prompt: "Describe a river.", words: ["the", "river", "froze", "solid", "during", "the", "coldest", "week", "of", "winter"], answer: "the river froze solid during the coldest week of winter" },
  { prompt: "Talk about a meeting.", words: ["the", "meeting", "started", "late", "because", "of", "technical", "problems"], answer: "the meeting started late because of technical problems" },
  { prompt: "Describe a voice.", words: ["her", "voice", "was", "soft", "but", "everyone", "in", "the", "room", "heard", "her"], answer: "her voice was soft but everyone in the room heard her" },
  { prompt: "Talk about a suitcase.", words: ["he", "packed", "his", "suitcase", "the", "night", "before", "the", "flight"], answer: "he packed his suitcase the night before the flight" },
  { prompt: "Describe a candle.", words: ["a", "single", "candle", "lit", "the", "small", "dark", "room"], answer: "a single candle lit the small dark room" },
  { prompt: "Talk about a password reset.", words: ["I", "had", "to", "reset", "my", "password", "after", "three", "failed", "attempts"], answer: "I had to reset my password after three failed attempts" },
  { prompt: "Describe a market.", words: ["vendors", "shouted", "prices", "above", "the", "noisy", "crowd"], answer: "vendors shouted prices above the noisy crowd" },
  { prompt: "Talk about a promise.", words: ["she", "kept", "her", "promise", "even", "when", "it", "was", "difficult"], answer: "she kept her promise even when it was difficult" },
  { prompt: "Describe a ladder.", words: ["he", "climbed", "the", "ladder", "to", "fix", "the", "broken", "gutter"], answer: "he climbed the ladder to fix the broken gutter" },
  { prompt: "Talk about a ticket.", words: ["we", "showed", "our", "tickets", "at", "the", "entrance", "to", "the", "museum"], answer: "we showed our tickets at the entrance to the museum" },
  { prompt: "Describe a mirror.", words: ["the", "mirror", "was", "cracked", "across", "one", "corner"], answer: "the mirror was cracked across one corner" },
  { prompt: "Talk about a schedule.", words: ["my", "schedule", "is", "too", "busy", "this", "week", "to", "meet"], answer: "my schedule is too busy this week to meet" },
  { prompt: "Describe a whistle.", words: ["the", "coach", "blew", "the", "whistle", "and", "practice", "began"], answer: "the coach blew the whistle and practice began" },
  { prompt: "Talk about a password hint.", words: ["never", "write", "your", "password", "hint", "where", "others", "can", "see", "it"], answer: "never write your password hint where others can see it" },
  { prompt: "Describe a fence.", words: ["they", "painted", "the", "fence", "white", "during", "the", "long", "weekend"], answer: "they painted the fence white during the long weekend" },
  { prompt: "Talk about a visa.", words: ["you", "need", "a", "visa", "to", "visit", "that", "country", "for", "work"], answer: "you need a visa to visit that country for work" },
  { prompt: "Describe a blanket.", words: ["the", "baby", "slept", "under", "a", "soft", "wool", "blanket"], answer: "the baby slept under a soft wool blanket" },
  { prompt: "Talk about a deadline.", words: ["we", "finished", "the", "project", "just", "before", "the", "deadline"], answer: "we finished the project just before the deadline" },
  { prompt: "Describe a hammer.", words: ["he", "used", "a", "hammer", "to", "hang", "the", "picture", "straight"], answer: "he used a hammer to hang the picture straight" },
  { prompt: "Talk about a discount.", words: ["the", "store", "offered", "a", "discount", "to", "students", "with", "ID"], answer: "the store offered a discount to students with ID" },
  { prompt: "Describe a tunnel.", words: ["the", "train", "disappeared", "into", "the", "long", "dark", "tunnel"], answer: "the train disappeared into the long dark tunnel" },
  { prompt: "Talk about a refund.", words: ["I", "asked", "for", "a", "refund", "because", "the", "item", "was", "damaged"], answer: "I asked for a refund because the item was damaged" },
  { prompt: "Describe a helmet.", words: ["always", "wear", "a", "helmet", "when", "you", "ride", "a", "motorbike"], answer: "always wear a helmet when you ride a motorbike" },
  { prompt: "Talk about a reservation.", words: ["we", "made", "a", "reservation", "at", "the", "restaurant", "for", "eight"], answer: "we made a reservation at the restaurant for eight" },
  { prompt: "Describe a valley.", words: ["mist", "filled", "the", "valley", "each", "cool", "spring", "morning"], answer: "mist filled the valley each cool spring morning" },
  { prompt: "Talk about a subscription.", words: ["I", "cancelled", "my", "subscription", "after", "the", "free", "trial", "ended"], answer: "I cancelled my subscription after the free trial ended" },
  { prompt: "Describe a telescope.", words: ["we", "looked", "through", "the", "telescope", "at", "Jupiter's", "moons"], answer: "we looked through the telescope at Jupiter's moons" },
  { prompt: "Talk about a complaint.", words: ["she", "filed", "a", "complaint", "about", "the", "noisy", "construction"], answer: "she filed a complaint about the noisy construction" },
  { prompt: "Describe a volcano.", words: ["smoke", "rose", "slowly", "from", "the", "distant", "volcano"], answer: "smoke rose slowly from the distant volcano" },
  { prompt: "Talk about a warranty.", words: ["the", "warranty", "covers", "repairs", "for", "two", "full", "years"], answer: "the warranty covers repairs for two full years" },
  { prompt: "Describe a compass.", words: ["the", "hiker", "checked", "the", "compass", "before", "leaving", "the", "trail"], answer: "the hiker checked the compass before leaving the trail" },
  { prompt: "Talk about an interview.", words: ["they", "asked", "difficult", "questions", "during", "the", "job", "interview"], answer: "they asked difficult questions during the job interview" },
  { prompt: "Describe a glacier.", words: ["the", "glacier", "moved", "only", "a", "few", "centimetres", "each", "year"], answer: "the glacier moved only a few centimetres each year" },
  { prompt: "Talk about a receipt.", words: ["keep", "your", "receipt", "in", "case", "you", "need", "to", "return", "it"], answer: "keep your receipt in case you need to return it" },
  { prompt: "Describe a desert.", words: ["heat", "shimmered", "above", "the", "empty", "golden", "desert"], answer: "heat shimmered above the empty golden desert" },
  { prompt: "Talk about a contract.", words: ["read", "the", "contract", "carefully", "before", "you", "sign", "anything"], answer: "read the contract carefully before you sign anything" },
  { prompt: "Describe a lighthouse.", words: ["the", "lighthouse", "beam", "swept", "across", "the", "dark", "harbour"], answer: "the lighthouse beam swept across the dark harbour" },
  { prompt: "Talk about a budget.", words: ["we", "stayed", "within", "our", "budget", "during", "the", "whole", "trip"], answer: "we stayed within our budget during the whole trip" },
  { prompt: "Describe a canyon.", words: ["echoes", "bounced", "between", "the", "tall", "canyon", "walls"], answer: "echoes bounced between the tall canyon walls" },
  { prompt: "Talk about a password manager.", words: ["a", "password", "manager", "can", "help", "you", "stay", "safe", "online"], answer: "a password manager can help you stay safe online" },
];
