/** Large vocabulary pool — daily sets of 6 are drawn for each of 90 rotation days. */
export const ALL_WORD_MATCH = [
  { word: "Brave", hint: "adjective", options: ["Afraid of everything", "Ready to face danger without fear", "Very lazy and slow", "Extremely hungry"], answer: 1 },
  { word: "Ancient", hint: "adjective", options: ["Very new and modern", "Belonging to a much earlier time", "Very small in size", "Extremely loud"], answer: 1 },
  { word: "Generous", hint: "adjective", options: ["Selfish with money", "Always angry at others", "Willing to give freely", "Difficult to understand"], answer: 2 },
  { word: "Exhausted", hint: "adjective", options: ["Full of energy", "Extremely tired", "Very happy", "Slightly confused"], answer: 1 },
  { word: "Enormous", hint: "adjective", options: ["Very tiny", "Quite pretty", "Extremely large", "A little warm"], answer: 2 },
  { word: "Grateful", hint: "adjective", options: ["Feeling thankful", "Feeling bored", "Feeling angry", "Feeling cold"], answer: 0 },
  { word: "Peculiar", hint: "adjective", options: ["Very common", "Strange or unusual", "Perfectly normal", "Beautiful to look at"], answer: 1 },
  { word: "Hesitate", hint: "verb", options: ["To run very fast", "To speak loudly", "To pause before acting", "To eat too much"], answer: 2 },
  { word: "Vibrant", hint: "adjective", options: ["Dull and lifeless", "Full of energy and colour", "Very quiet", "Easily broken"], answer: 1 },
  { word: "Cautious", hint: "adjective", options: ["Reckless and bold", "Careful to avoid danger", "Very generous", "Loud and noisy"], answer: 1 },
  { word: "Stubborn", hint: "adjective", options: ["Very flexible", "Unwilling to change one's mind", "Extremely kind", "Slightly nervous"], answer: 1 },
  { word: "Admire", hint: "verb", options: ["To dislike strongly", "To look at with respect and pleasure", "To forget quickly", "To argue loudly"], answer: 1 },
  { word: "Cozy", hint: "adjective", options: ["Cold and uncomfortable", "Comfortable and warm", "Very noisy", "Difficult and stressful"], answer: 1 },
  { word: "Thrive", hint: "verb", options: ["To struggle greatly", "To grow and do well", "To sleep deeply", "To move slowly"], answer: 1 },
  { word: "Gloomy", hint: "adjective", options: ["Bright and cheerful", "Dark and sad", "Very exciting", "Extremely clean"], answer: 1 },
  { word: "Eager", hint: "adjective", options: ["Bored and uninterested", "Very keen and enthusiastic", "Slow and cautious", "Quiet and shy"], answer: 1 },
  { word: "Fragile", hint: "adjective", options: ["Very strong and tough", "Easily broken or damaged", "Extremely large", "Loud and confident"], answer: 1 },
  { word: "Wander", hint: "verb", options: ["To stay in one place", "To walk without a fixed direction", "To sleep outdoors", "To eat quickly"], answer: 1 },
  { word: "Sincere", hint: "adjective", options: ["Dishonest and fake", "Genuine and honest", "Very lazy", "Quite rude"], answer: 1 },
  { word: "Scarce", hint: "adjective", options: ["Very common and plentiful", "Available in small amounts", "Extremely large", "Very loud"], answer: 1 },
  { word: "Triumph", hint: "noun", options: ["A great failure", "A great victory or success", "A long journey", "A delicious meal"], answer: 1 },
  { word: "Blissful", hint: "adjective", options: ["Angry and upset", "Perfectly happy and content", "Very cold", "Quite tired"], answer: 1 },
  { word: "Discard", hint: "verb", options: ["To keep carefully", "To throw away as useless", "To repair something", "To find something lost"], answer: 1 },
  { word: "Tranquil", hint: "adjective", options: ["Loud and chaotic", "Calm and peaceful", "Very dark", "Extremely busy"], answer: 1 },
  { word: "Cunning", hint: "adjective", options: ["Honest and open", "Clever in a sneaky way", "Very slow", "Extremely kind"], answer: 1 },
  { word: "Abundant", hint: "adjective", options: ["Very scarce", "Available in large quantities", "Quite boring", "Very small"], answer: 1 },
  { word: "Cherish", hint: "verb", options: ["To ignore or neglect", "To hold dear and care for", "To break apart", "To forget forever"], answer: 1 },
  { word: "Dreadful", hint: "adjective", options: ["Wonderful and amazing", "Very bad or unpleasant", "Quite comfortable", "Slightly cold"], answer: 1 },
  { word: "Reluctant", hint: "adjective", options: ["Very willing", "Unwilling or hesitant", "Extremely loud", "Always cheerful"], answer: 1 },
  { word: "Precise", hint: "adjective", options: ["Vague and unclear", "Exact and accurate", "Very slow", "Quite angry"], answer: 1 },
  { word: "Furious", hint: "adjective", options: ["Very calm", "Extremely angry", "Slightly cold", "Quite happy"], answer: 1 },
  { word: "Humble", hint: "adjective", options: ["Very proud and boastful", "Modest and not arrogant", "Extremely loud", "Quite lazy"], answer: 1 },
  { word: "Reliable", hint: "adjective", options: ["Often failing", "Dependable and trustworthy", "Very noisy", "Quite rude"], answer: 1 },
  { word: "Hostile", hint: "adjective", options: ["Friendly and kind", "Unfriendly or aggressive", "Very quiet", "Quite small"], answer: 1 },
  { word: "Plentiful", hint: "adjective", options: ["Very rare", "Available in great amounts", "Quite boring", "Very tiny"], answer: 1 },
  { word: "Timid", hint: "adjective", options: ["Very brave", "Shy and not confident", "Extremely loud", "Quite rude"], answer: 1 },
  { word: "Vague", hint: "adjective", options: ["Clear and specific", "Unclear or imprecise", "Very fast", "Quite small"], answer: 1 },
  { word: "Ruthless", hint: "adjective", options: ["Very gentle and kind", "Cruel and showing no mercy", "Quite shy", "Very slow"], answer: 1 },
  { word: "Luminous", hint: "adjective", options: ["Very dark", "Bright or shining", "Quite cold", "Very small"], answer: 1 },
  { word: "Meager", hint: "adjective", options: ["Large and generous", "Small in quantity", "Very bright", "Quite fast"], answer: 1 },
  { word: "Ordeal", hint: "noun", options: ["A pleasant trip", "A difficult experience", "A small meal", "A quiet room"], answer: 1 },
  { word: "Resilient", hint: "adjective", options: ["Easily broken", "Able to recover quickly", "Very lazy", "Quite loud"], answer: 1 },
  { word: "Obsolete", hint: "adjective", options: ["Modern and current", "No longer used", "Very popular", "Quite new"], answer: 1 },
  { word: "Elaborate", hint: "adjective", options: ["Very simple", "Detailed and complex", "Quite small", "Very fast"], answer: 1 },
  { word: "Frugal", hint: "adjective", options: ["Spending freely", "Careful with money", "Very loud", "Quite rude"], answer: 1 },
  { word: "Oblivious", hint: "adjective", options: ["Very aware", "Unaware of what is happening", "Quite brave", "Very fast"], answer: 1 },
  { word: "Redundant", hint: "adjective", options: ["Essential", "No longer needed", "Very new", "Quite small"], answer: 1 },
  { word: "Subtle", hint: "adjective", options: ["Obvious and loud", "Not obvious; delicate", "Very big", "Quite angry"], answer: 1 },
  { word: "Volatile", hint: "adjective", options: ["Very stable", "Likely to change suddenly", "Quite calm", "Very slow"], answer: 1 },
  { word: "Zealous", hint: "adjective", options: ["Uninterested", "Very enthusiastic", "Quite lazy", "Very shy"], answer: 1 },
  { word: "Adept", hint: "adjective", options: ["Very clumsy", "Skilled at something", "Quite slow", "Very loud"], answer: 1 },
  { word: "Benevolent", hint: "adjective", options: ["Cruel and mean", "Kind and generous", "Very shy", "Quite lazy"], answer: 1 },
  { word: "Callous", hint: "adjective", options: ["Very sensitive", "Cruel and without sympathy", "Quite kind", "Very small"], answer: 1 },
  { word: "Diligent", hint: "adjective", options: ["Lazy and careless", "Hard-working and careful", "Very loud", "Quite shy"], answer: 1 },
  { word: "Erratic", hint: "adjective", options: ["Steady and predictable", "Unpredictable; irregular", "Very calm", "Quite kind"], answer: 1 },
  { word: "Feasible", hint: "adjective", options: ["Impossible", "Possible to do", "Very rare", "Quite loud"], answer: 1 },
  { word: "Grim", hint: "adjective", options: ["Cheerful and bright", "Serious and unpleasant", "Very small", "Quite fast"], answer: 1 },
  { word: "Haphazard", hint: "adjective", options: ["Organized and careful", "Random and careless", "Very calm", "Quite kind"], answer: 1 },
  { word: "Imminent", hint: "adjective", options: ["Far in the future", "About to happen soon", "Very old", "Quite small"], answer: 1 },
  { word: "Jovial", hint: "adjective", options: ["Sad and serious", "Cheerful and friendly", "Very shy", "Quite lazy"], answer: 1 },
  { word: "Keen", hint: "adjective", options: ["Not interested", "Eager and enthusiastic", "Very slow", "Quite loud"], answer: 1 },
  { word: "Lucid", hint: "adjective", options: ["Confusing", "Clear and easy to understand", "Very dark", "Quite small"], answer: 1 },
  { word: "Meticulous", hint: "adjective", options: ["Careless", "Very careful about details", "Very fast", "Quite loud"], answer: 1 },
  { word: "Nimble", hint: "adjective", options: ["Slow and clumsy", "Quick and light in movement", "Very heavy", "Quite lazy"], answer: 1 },
  { word: "Ominous", hint: "adjective", options: ["Reassuring", "Suggesting something bad will happen", "Very bright", "Quite small"], answer: 1 },
  { word: "Pragmatic", hint: "adjective", options: ["Unrealistic", "Practical and realistic", "Very shy", "Quite loud"], answer: 1 },
  { word: "Quaint", hint: "adjective", options: ["Modern and plain", "Charmingly old-fashioned", "Very loud", "Quite rude"], answer: 1 },
  { word: "Robust", hint: "adjective", options: ["Weak and delicate", "Strong and healthy", "Very small", "Quite slow"], answer: 1 },
  { word: "Sparse", hint: "adjective", options: ["Crowded and thick", "Thinly scattered", "Very loud", "Quite fast"], answer: 1 },
  { word: "Tedious", hint: "adjective", options: ["Exciting", "Boring and too long", "Very short", "Quite loud"], answer: 1 },
  { word: "Utter", hint: "adjective", options: ["Partial", "Complete or absolute", "Very small", "Quite slow"], answer: 1 },
  { word: "Vivid", hint: "adjective", options: ["Dull and pale", "Bright and clear", "Very quiet", "Quite small"], answer: 1 },
  { word: "Wary", hint: "adjective", options: ["Careless about danger", "Cautious and watchful", "Very loud", "Quite lazy"], answer: 1 },
  { word: "Yearn", hint: "verb", options: ["To feel no desire", "To want something strongly", "To run away", "To forget"], answer: 1 },
  { word: "Zest", hint: "noun", options: ["Lack of interest", "Great enthusiasm", "A type of tool", "A loud noise"], answer: 1 },
  { word: "Acrid", hint: "adjective", options: ["Sweet smelling", "Sharp and bitter in smell or taste", "Very soft", "Quite cold"], answer: 1 },
  { word: "Brash", hint: "adjective", options: ["Quiet and polite", "Too confident in a rude way", "Very small", "Quite slow"], answer: 1 },
  { word: "Crave", hint: "verb", options: ["To dislike strongly", "To want something very much", "To throw away", "To hide"], answer: 1 },
  { word: "Daunt", hint: "verb", options: ["To encourage", "To make someone lose courage", "To help quickly", "To forget"], answer: 1 },
  { word: "Edgy", hint: "adjective", options: ["Very calm", "Nervous or tense", "Quite old", "Very soft"], answer: 1 },
  { word: "Fickle", hint: "adjective", options: ["Always the same", "Changing often; not loyal", "Very kind", "Quite slow"], answer: 1 },
  { word: "Gripe", hint: "verb", options: ["To praise loudly", "To complain constantly", "To run fast", "To sleep"], answer: 1 },
  { word: "Hoarse", hint: "adjective", options: ["Clear voiced", "Rough sounding (voice)", "Very bright", "Quite small"], answer: 1 },
  { word: "Inept", hint: "adjective", options: ["Skilled", "Clumsy and unskilled", "Very fast", "Quite kind"], answer: 1 },
  { word: "Jaded", hint: "adjective", options: ["Fresh and excited", "Tired and bored from too much", "Very young", "Quite loud"], answer: 1 },
  { word: "Kindle", hint: "verb", options: ["To put out a fire", "To start a fire or feeling", "To break glass", "To hide"], answer: 1 },
  { word: "Lethal", hint: "adjective", options: ["Harmless", "Deadly", "Very small", "Quite soft"], answer: 1 },
  { word: "Mellow", hint: "adjective", options: ["Harsh and bright", "Soft, rich, relaxed", "Very loud", "Quite fast"], answer: 1 },
  { word: "Nurture", hint: "verb", options: ["To ignore", "To care for and help grow", "To break", "To forget"], answer: 1 },
  { word: "Ostracize", hint: "verb", options: ["To welcome warmly", "To exclude from a group", "To praise", "To follow"], answer: 1 },
  { word: "Placid", hint: "adjective", options: ["Stormy and wild", "Calm and peaceful", "Very loud", "Quite fast"], answer: 1 },
  { word: "Quell", hint: "verb", options: ["To start a fight", "To stop something by force", "To build", "To sing"], answer: 1 },
  { word: "Ravenous", hint: "adjective", options: ["Not hungry at all", "Extremely hungry", "Very full", "Quite slow"], answer: 1 },
  { word: "Savory", hint: "adjective", options: ["Sweet like candy", "Salty or spicy tasting", "Very cold", "Quite soft"], answer: 1 },
  { word: "Tacit", hint: "adjective", options: ["Said out loud", "Understood without being spoken", "Very loud", "Quite slow"], answer: 1 },
  { word: "Usher", hint: "verb", options: ["To push away", "To show someone to a seat", "To break", "To hide"], answer: 1 },
  { word: "Veer", hint: "verb", options: ["To go straight", "To change direction suddenly", "To stop", "To wait"], answer: 1 },
  { word: "Wry", hint: "adjective", options: ["Serious and dull", "Humorous in a clever dry way", "Very loud", "Quite young"], answer: 1 },
];
