/**
 * In-app Privacy Policy for English Everyday Play.
 * Review with legal counsel before production; update “Last updated” when you change practices.
 */
export function PrivacyPolicyPage({ onClose }) {
  return (
    <div className="result-page legal-page-wrap" role="document">
      <div className="result-page-header">
        <button type="button" className="btn-secondary" onClick={onClose}>
          ← Back to Homepage
        </button>
      </div>
      <div className="result-page-content">
        <article className="legal-article">
          <h1 className="legal-title">Privacy Policy</h1>
          <p className="legal-meta">English Everyday Play (“we”, “us”, “our”)</p>
          <p className="legal-meta">
            <strong>Last updated:</strong> 19 March 2026
          </p>

          <section className="legal-section">
            <h2>1. Who we are</h2>
            <p>
              This website and web app (“<strong>Service</strong>”) is operated for English Everyday Play, a vocabulary and language
              practice experience. This policy explains how we handle information when you use the Service on your device.
            </p>
          </section>

          <section className="legal-section">
            <h2>2. Summary</h2>
            <ul className="legal-list">
              <li>
                <strong>Local-first:</strong> Game progress, optional accounts, and archives are stored mainly in your browser’s{" "}
                <strong>local storage</strong> on your device—not on our servers (this app has no login server in the default setup).
              </li>
              <li>
                <strong>Cookies &amp; similar tech:</strong> We use a consent banner for optional categories. Strictly necessary storage
                is needed to run the games and sign-in state on your device.
              </li>
              <li>
                <strong>Third-party sites:</strong> If you use “Share”, “Donate”, or similar links, those services have their own
                privacy policies.
              </li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>3. Information we process</h2>
            <h3>3.1 You provide</h3>
            <ul className="legal-list">
              <li>
                <strong>Account (optional):</strong> If you create an account to use archive or related features, you may provide an
                email address, password, and optional classroom/student code. In the default configuration this is stored only in your
                browser’s local storage on your device. Your sign-in session is remembered for up to <strong>7 days</strong> (extended
                when you use the app again while still signed in); after that you’ll need to sign in again.
              </li>
              <li>
                <strong>School interest (optional):</strong> If you use the “For schools &amp; teachers” form on the homepage, you may
                provide a work email and optional school name. In the default configuration, submissions are stored only in your browser’s
                local storage under the key <code>wordplay-school-interest-leads</code> (not sent to our servers) until a dedicated school
                signup or portal is available.
              </li>
            </ul>
            <h3>3.2 Generated by use of the Service</h3>
            <ul className="legal-list">
              <li>
                <strong>Gameplay data:</strong> Daily progress, scores, completion flags, and in-app archive copies of past days.
              </li>
              <li>
                <strong>Technical data:</strong> Standard browser data (e.g. user agent) may be visible to whoever hosts the site files
                (e.g. static hosting or CDN logs). This app does not require a separate analytics SDK by default.
              </li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>4. Legal bases (UK / EEA)</h2>
            <p>Where UK GDPR / EU GDPR applies, we rely on:</p>
            <ul className="legal-list">
              <li>
                <strong>Strictly necessary storage</strong> — to provide the Service you request (running games, remembering progress and
                optional account on your device).
              </li>
              <li>
                <strong>Consent</strong> — for optional cookies or similar technologies when you accept them in our cookie notice.
              </li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>5. Cookies, local storage, and consent</h2>
            <p>
              We distinguish <strong>strictly necessary</strong> storage (needed for the app to function on your device) from{" "}
              <strong>optional</strong> categories such as analytics or marketing/social measurement. Optional categories are off unless
              you opt in. You can reopen <strong>Cookie settings</strong> in the footer to change your choice.
            </p>
            <p>
              Your consent choices are stored locally (e.g. under the key <code>wordplay-cookie-consent</code>) so we can respect them
              on return visits.
            </p>
            <p>
              If your browser receives an approximate country from our optional ipapi.co lookup (see below), we may store the ISO country
              code locally under <code>wordplay-estimated-country</code> so the in-app statistics view can highlight your region on an
              illustrative world map. This remains on your device in the default setup.
            </p>
          </section>

          <section className="legal-section">
            <h2>6. Third-party services</h2>
            <p>Parts of the Service link out to third parties, for example:</p>
            <ul className="legal-list">
              <li>
                <strong>Buy Me a Coffee</strong> — for optional support/donations (
                <a href="https://buymeacoffee.com/privacy" target="_blank" rel="noopener noreferrer">
                  their privacy policy
                </a>
                ).
              </li>
              <li>
                <strong>Social sharing</strong> — e.g. Facebook when you choose “Share”; those platforms set their own cookies and process
                data under their policies.
              </li>
              <li>
                <strong>ipapi.co</strong> — we may request your approximate country (from your IP) to suggest a default UI language when
                you have not already chosen one, and/or to store an approximate country code for the statistics map highlight. The request is
                sent directly from your browser to ipapi.co; see{" "}
                <a href="https://ipapi.co/privacy" target="_blank" rel="noopener noreferrer">
                  their privacy policy
                </a>
                . Language and country estimates are stored locally where applicable so we do not need to repeat the request unnecessarily.
              </li>
            </ul>
            <p>We do not control third-party sites. Please read their policies before using them.</p>
          </section>

          <section className="legal-section">
            <h2>7. Children</h2>
            <p>
              The Service is intended for learners. If you are under the age at which parental consent is required in your country,
              use the Service only with a parent or guardian’s permission. We do not knowingly collect personal information beyond what is
              stored locally for gameplay in the manner described above. If you believe a child has provided information inappropriately,
              contact us (see below).
            </p>
          </section>

          <section className="legal-section">
            <h2>8. Retention</h2>
            <p>
              Data stored in your browser remains until you clear site data, uninstall the browser, or we ship an update that changes
              storage keys. You can remove accounts and progress by clearing storage for this site or using browser settings.
            </p>
          </section>

          <section className="legal-section">
            <h2>9. International transfers</h2>
            <p>
              Because data in the default setup stays on your device, there is no separate transfer by us to another country for that
              local data. Third-party services you choose (e.g. payment or social sites) may process data globally under their own terms.
            </p>
          </section>

          <section className="legal-section">
            <h2>10. Your rights (UK / EEA)</h2>
            <p>Depending on where you live, you may have rights to:</p>
            <ul className="legal-list">
              <li>Access, correct, or delete personal data we hold (where we act as controller);</li>
              <li>Restrict or object to certain processing;</li>
              <li>Data portability, where applicable;</li>
              <li>Withdraw consent for optional cookies at any time (without affecting prior lawful use);</li>
              <li>Lodge a complaint with a supervisory authority (e.g. ICO in the UK).</li>
            </ul>
            <p>
              For purely local browser storage, you can exercise many rights directly via browser controls and our in-app settings
              where available.
            </p>
          </section>

          <section className="legal-section">
            <h2>11. Security</h2>
            <p>
              Passwords and accounts in the default build are stored locally on your device. Anyone with access to your device or
              browser profile may access that data. Use a strong password and protect your device. If you deploy a version with server
              sign-in, update this policy and your security measures accordingly.
            </p>
          </section>

          <section className="legal-section">
            <h2>12. Changes</h2>
            <p>
              We may update this policy from time to time. We will adjust the “Last updated” date and, where appropriate, show a notice
              in the app or ask for consent again if required.
            </p>
          </section>

          <section className="legal-section">
            <h2>13. Contact</h2>
            <p>
              Questions about this policy or your data: reach out via{" "}
              <a href="https://buymeacoffee.com/englisheverydayplay" target="_blank" rel="noopener noreferrer">
                Buy Me a Coffee — English Everyday Play
              </a>{" "}
              or the contact details you publish for your project. Replace this section with a dedicated email if you add one.
            </p>
          </section>

          <div className="legal-actions">
            <button type="button" className="btn-primary" onClick={onClose}>
              Back to games
            </button>
          </div>
        </article>
      </div>
    </div>
  );
}
